//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyConcertDataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class MyConcertDBEntities : DbContext
    {
        public MyConcertDBEntities()
            : base("name=MyConcertDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual int P_IniSesion(string correo, string contrasena, ObjectParameter tipoUsuario)
        {
            var correoParameter = correo != null ?
                new ObjectParameter("Correo", correo) :
                new ObjectParameter("Correo", typeof(string));
    
            var contrasenaParameter = contrasena != null ?
                new ObjectParameter("Contrasena", contrasena) :
                new ObjectParameter("Contrasena", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("P_IniSesion", correoParameter, contrasenaParameter, tipoUsuario);
        }
    
        public virtual int P_RegistrarCategoria(string nombreCategoria, ObjectParameter exito)
        {
            var nombreCategoriaParameter = nombreCategoria != null ?
                new ObjectParameter("NombreCategoria", nombreCategoria) :
                new ObjectParameter("NombreCategoria", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("P_RegistrarCategoria", nombreCategoriaParameter, exito);
        }
    
        public virtual int P_RegistrarColaborador(string correo, string contrasena, string nombreUsuario, string apellidoUsuario, ObjectParameter exito)
        {
            var correoParameter = correo != null ?
                new ObjectParameter("Correo", correo) :
                new ObjectParameter("Correo", typeof(string));
    
            var contrasenaParameter = contrasena != null ?
                new ObjectParameter("Contrasena", contrasena) :
                new ObjectParameter("Contrasena", typeof(string));
    
            var nombreUsuarioParameter = nombreUsuario != null ?
                new ObjectParameter("NombreUsuario", nombreUsuario) :
                new ObjectParameter("NombreUsuario", typeof(string));
    
            var apellidoUsuarioParameter = apellidoUsuario != null ?
                new ObjectParameter("ApellidoUsuario", apellidoUsuario) :
                new ObjectParameter("ApellidoUsuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("P_RegistrarColaborador", correoParameter, contrasenaParameter, nombreUsuarioParameter, apellidoUsuarioParameter, exito);
        }
    
        public virtual int P_RegistrarFanatico(string correo, string contrasena, string nombreUsuario, string apellidoUsuario, string paisFanatico, string ubicacionFanatico, string universidad, string telefono, string uRL_Foto, string descripcionPersonal, Nullable<System.DateTime> fechaNacimiento, ObjectParameter exito)
        {
            var correoParameter = correo != null ?
                new ObjectParameter("Correo", correo) :
                new ObjectParameter("Correo", typeof(string));
    
            var contrasenaParameter = contrasena != null ?
                new ObjectParameter("Contrasena", contrasena) :
                new ObjectParameter("Contrasena", typeof(string));
    
            var nombreUsuarioParameter = nombreUsuario != null ?
                new ObjectParameter("NombreUsuario", nombreUsuario) :
                new ObjectParameter("NombreUsuario", typeof(string));
    
            var apellidoUsuarioParameter = apellidoUsuario != null ?
                new ObjectParameter("ApellidoUsuario", apellidoUsuario) :
                new ObjectParameter("ApellidoUsuario", typeof(string));
    
            var paisFanaticoParameter = paisFanatico != null ?
                new ObjectParameter("PaisFanatico", paisFanatico) :
                new ObjectParameter("PaisFanatico", typeof(string));
    
            var ubicacionFanaticoParameter = ubicacionFanatico != null ?
                new ObjectParameter("UbicacionFanatico", ubicacionFanatico) :
                new ObjectParameter("UbicacionFanatico", typeof(string));
    
            var universidadParameter = universidad != null ?
                new ObjectParameter("Universidad", universidad) :
                new ObjectParameter("Universidad", typeof(string));
    
            var telefonoParameter = telefono != null ?
                new ObjectParameter("Telefono", telefono) :
                new ObjectParameter("Telefono", typeof(string));
    
            var uRL_FotoParameter = uRL_Foto != null ?
                new ObjectParameter("URL_Foto", uRL_Foto) :
                new ObjectParameter("URL_Foto", typeof(string));
    
            var descripcionPersonalParameter = descripcionPersonal != null ?
                new ObjectParameter("DescripcionPersonal", descripcionPersonal) :
                new ObjectParameter("DescripcionPersonal", typeof(string));
    
            var fechaNacimientoParameter = fechaNacimiento.HasValue ?
                new ObjectParameter("FechaNacimiento", fechaNacimiento) :
                new ObjectParameter("FechaNacimiento", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("P_RegistrarFanatico", correoParameter, contrasenaParameter, nombreUsuarioParameter, apellidoUsuarioParameter, paisFanaticoParameter, ubicacionFanaticoParameter, universidadParameter, telefonoParameter, uRL_FotoParameter, descripcionPersonalParameter, fechaNacimientoParameter, exito);
        }
    
        public virtual int P_RegistrarGeneroMusical(string nombreGeneroMusical, ObjectParameter exito)
        {
            var nombreGeneroMusicalParameter = nombreGeneroMusical != null ?
                new ObjectParameter("NombreGeneroMusical", nombreGeneroMusical) :
                new ObjectParameter("NombreGeneroMusical", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("P_RegistrarGeneroMusical", nombreGeneroMusicalParameter, exito);
        }
    
        public virtual int P_RegistrarPais(string nombrePais, ObjectParameter exito)
        {
            var nombrePaisParameter = nombrePais != null ?
                new ObjectParameter("NombrePais", nombrePais) :
                new ObjectParameter("NombrePais", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("P_RegistrarPais", nombrePaisParameter, exito);
        }
    
        public virtual ObjectResult<P_V_Colaborador_Result> P_V_Colaborador(Nullable<int> idUsuario)
        {
            var idUsuarioParameter = idUsuario.HasValue ?
                new ObjectParameter("IdUsuario", idUsuario) :
                new ObjectParameter("IdUsuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<P_V_Colaborador_Result>("P_V_Colaborador", idUsuarioParameter);
        }
    
        public virtual ObjectResult<P_V_Fanatico_Result> P_V_Fanatico(Nullable<int> idUsuario)
        {
            var idUsuarioParameter = idUsuario.HasValue ?
                new ObjectParameter("IdUsuario", idUsuario) :
                new ObjectParameter("IdUsuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<P_V_Fanatico_Result>("P_V_Fanatico", idUsuarioParameter);
        }
    
        public virtual ObjectResult<P_V_Pais_Result> P_V_Pais()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<P_V_Pais_Result>("P_V_Pais");
        }
    }
}
